import _defineProperty from "@babel/runtime/helpers/esm/defineProperty";

/**
 * This file was automatically generated by cosmwasm-typescript-gen@0.3.6.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the cosmwasm-typescript-gen generate command to regenerate this file.
 */
export class Cw20QueryClient {
  constructor(client, contractAddress) {
    _defineProperty(this, "client", void 0);

    _defineProperty(this, "contractAddress", void 0);

    _defineProperty(this, "balance", async ({
      address
    }) => {
      return this.client.queryContractSmart(this.contractAddress, {
        balance: {
          address
        }
      });
    });

    _defineProperty(this, "tokenInfo", async () => {
      return this.client.queryContractSmart(this.contractAddress, {
        token_info: {}
      });
    });

    _defineProperty(this, "minter", async () => {
      return this.client.queryContractSmart(this.contractAddress, {
        minter: {}
      });
    });

    _defineProperty(this, "allowance", async ({
      owner,
      spender
    }) => {
      return this.client.queryContractSmart(this.contractAddress, {
        allowance: {
          owner,
          spender
        }
      });
    });

    _defineProperty(this, "allAllowances", async ({
      limit,
      owner,
      startAfter
    }) => {
      return this.client.queryContractSmart(this.contractAddress, {
        all_allowances: {
          limit,
          owner,
          start_after: startAfter
        }
      });
    });

    _defineProperty(this, "allAccounts", async ({
      limit,
      startAfter
    }) => {
      return this.client.queryContractSmart(this.contractAddress, {
        all_accounts: {
          limit,
          start_after: startAfter
        }
      });
    });

    _defineProperty(this, "marketingInfo", async () => {
      return this.client.queryContractSmart(this.contractAddress, {
        marketing_info: {}
      });
    });

    _defineProperty(this, "downloadLogo", async () => {
      return this.client.queryContractSmart(this.contractAddress, {
        download_logo: {}
      });
    });

    this.client = client;
    this.contractAddress = contractAddress;
    this.balance = this.balance.bind(this);
    this.tokenInfo = this.tokenInfo.bind(this);
    this.minter = this.minter.bind(this);
    this.allowance = this.allowance.bind(this);
    this.allAllowances = this.allAllowances.bind(this);
    this.allAccounts = this.allAccounts.bind(this);
    this.marketingInfo = this.marketingInfo.bind(this);
    this.downloadLogo = this.downloadLogo.bind(this);
  }

}