import _defineProperty from "@babel/runtime/helpers/esm/defineProperty";

/**
 * This file was automatically generated by cosmwasm-typescript-gen@0.3.6.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the cosmwasm-typescript-gen generate command to regenerate this file.
 */
export class Cw20Ics20QueryClient {
  constructor(client, contractAddress) {
    _defineProperty(this, "client", void 0);

    _defineProperty(this, "contractAddress", void 0);

    _defineProperty(this, "port", async () => {
      return this.client.queryContractSmart(this.contractAddress, {
        port: {}
      });
    });

    _defineProperty(this, "listChannels", async () => {
      return this.client.queryContractSmart(this.contractAddress, {
        list_channels: {}
      });
    });

    _defineProperty(this, "channel", async ({
      id
    }) => {
      return this.client.queryContractSmart(this.contractAddress, {
        channel: {
          id
        }
      });
    });

    _defineProperty(this, "config", async () => {
      return this.client.queryContractSmart(this.contractAddress, {
        config: {}
      });
    });

    _defineProperty(this, "admin", async () => {
      return this.client.queryContractSmart(this.contractAddress, {
        admin: {}
      });
    });

    _defineProperty(this, "allowed", async ({
      contract
    }) => {
      return this.client.queryContractSmart(this.contractAddress, {
        allowed: {
          contract
        }
      });
    });

    _defineProperty(this, "listAllowed", async ({
      limit,
      startAfter
    }) => {
      return this.client.queryContractSmart(this.contractAddress, {
        list_allowed: {
          limit,
          start_after: startAfter
        }
      });
    });

    this.client = client;
    this.contractAddress = contractAddress;
    this.port = this.port.bind(this);
    this.listChannels = this.listChannels.bind(this);
    this.channel = this.channel.bind(this);
    this.config = this.config.bind(this);
    this.admin = this.admin.bind(this);
    this.allowed = this.allowed.bind(this);
    this.listAllowed = this.listAllowed.bind(this);
  }

}
export class Cw20Ics20Client extends Cw20Ics20QueryClient {
  constructor(client, _sender, contractAddress) {
    super(client, contractAddress);

    _defineProperty(this, "client", void 0);

    _defineProperty(this, "sender", void 0);

    _defineProperty(this, "contractAddress", void 0);

    _defineProperty(this, "receive", async ({
      amount,
      msg,
      sender
    }, fee = "auto", memo, funds) => {
      return await this.client.execute(this.sender, this.contractAddress, {
        receive: {
          amount,
          msg,
          sender
        }
      }, fee, memo, funds);
    });

    _defineProperty(this, "transfer", async ({
      channel,
      remoteAddress,
      timeout
    }, fee = "auto", memo, funds) => {
      return await this.client.execute(this.sender, this.contractAddress, {
        transfer: {
          channel,
          remote_address: remoteAddress,
          timeout
        }
      }, fee, memo, funds);
    });

    _defineProperty(this, "allow", async ({
      contract,
      gasLimit
    }, fee = "auto", memo, funds) => {
      return await this.client.execute(this.sender, this.contractAddress, {
        allow: {
          contract,
          gas_limit: gasLimit
        }
      }, fee, memo, funds);
    });

    _defineProperty(this, "updateAdmin", async ({
      admin
    }, fee = "auto", memo, funds) => {
      return await this.client.execute(this.sender, this.contractAddress, {
        update_admin: {
          admin
        }
      }, fee, memo, funds);
    });

    this.client = client;
    this.sender = _sender;
    this.contractAddress = contractAddress;
    this.receive = this.receive.bind(this);
    this.transfer = this.transfer.bind(this);
    this.allow = this.allow.bind(this);
    this.updateAdmin = this.updateAdmin.bind(this);
  }

}