"use strict";

var _interopRequireDefault = require("@babel/runtime/helpers/interopRequireDefault");

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.Cw20QueryClient = void 0;

var _regenerator = _interopRequireDefault(require("@babel/runtime/regenerator"));

var _asyncToGenerator2 = _interopRequireDefault(require("@babel/runtime/helpers/asyncToGenerator"));

var _createClass2 = _interopRequireDefault(require("@babel/runtime/helpers/createClass"));

var _classCallCheck2 = _interopRequireDefault(require("@babel/runtime/helpers/classCallCheck"));

var _defineProperty2 = _interopRequireDefault(require("@babel/runtime/helpers/defineProperty"));

/**
* This file was automatically generated by cosmwasm-typescript-gen@0.3.6.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the cosmwasm-typescript-gen generate command to regenerate this file.
*/
var Cw20QueryClient = /*#__PURE__*/(0, _createClass2["default"])(function Cw20QueryClient(client, contractAddress) {
  var _this = this;

  (0, _classCallCheck2["default"])(this, Cw20QueryClient);
  (0, _defineProperty2["default"])(this, "client", void 0);
  (0, _defineProperty2["default"])(this, "contractAddress", void 0);
  (0, _defineProperty2["default"])(this, "balance", /*#__PURE__*/function () {
    var _ref2 = (0, _asyncToGenerator2["default"])( /*#__PURE__*/_regenerator["default"].mark(function _callee(_ref) {
      var address;
      return _regenerator["default"].wrap(function _callee$(_context) {
        while (1) {
          switch (_context.prev = _context.next) {
            case 0:
              address = _ref.address;
              return _context.abrupt("return", _this.client.queryContractSmart(_this.contractAddress, {
                balance: {
                  address: address
                }
              }));

            case 2:
            case "end":
              return _context.stop();
          }
        }
      }, _callee);
    }));

    return function (_x) {
      return _ref2.apply(this, arguments);
    };
  }());
  (0, _defineProperty2["default"])(this, "tokenInfo", /*#__PURE__*/(0, _asyncToGenerator2["default"])( /*#__PURE__*/_regenerator["default"].mark(function _callee2() {
    return _regenerator["default"].wrap(function _callee2$(_context2) {
      while (1) {
        switch (_context2.prev = _context2.next) {
          case 0:
            return _context2.abrupt("return", _this.client.queryContractSmart(_this.contractAddress, {
              token_info: {}
            }));

          case 1:
          case "end":
            return _context2.stop();
        }
      }
    }, _callee2);
  })));
  (0, _defineProperty2["default"])(this, "minter", /*#__PURE__*/(0, _asyncToGenerator2["default"])( /*#__PURE__*/_regenerator["default"].mark(function _callee3() {
    return _regenerator["default"].wrap(function _callee3$(_context3) {
      while (1) {
        switch (_context3.prev = _context3.next) {
          case 0:
            return _context3.abrupt("return", _this.client.queryContractSmart(_this.contractAddress, {
              minter: {}
            }));

          case 1:
          case "end":
            return _context3.stop();
        }
      }
    }, _callee3);
  })));
  (0, _defineProperty2["default"])(this, "allowance", /*#__PURE__*/function () {
    var _ref6 = (0, _asyncToGenerator2["default"])( /*#__PURE__*/_regenerator["default"].mark(function _callee4(_ref5) {
      var owner, spender;
      return _regenerator["default"].wrap(function _callee4$(_context4) {
        while (1) {
          switch (_context4.prev = _context4.next) {
            case 0:
              owner = _ref5.owner, spender = _ref5.spender;
              return _context4.abrupt("return", _this.client.queryContractSmart(_this.contractAddress, {
                allowance: {
                  owner: owner,
                  spender: spender
                }
              }));

            case 2:
            case "end":
              return _context4.stop();
          }
        }
      }, _callee4);
    }));

    return function (_x2) {
      return _ref6.apply(this, arguments);
    };
  }());
  (0, _defineProperty2["default"])(this, "allAllowances", /*#__PURE__*/function () {
    var _ref8 = (0, _asyncToGenerator2["default"])( /*#__PURE__*/_regenerator["default"].mark(function _callee5(_ref7) {
      var limit, owner, startAfter;
      return _regenerator["default"].wrap(function _callee5$(_context5) {
        while (1) {
          switch (_context5.prev = _context5.next) {
            case 0:
              limit = _ref7.limit, owner = _ref7.owner, startAfter = _ref7.startAfter;
              return _context5.abrupt("return", _this.client.queryContractSmart(_this.contractAddress, {
                all_allowances: {
                  limit: limit,
                  owner: owner,
                  start_after: startAfter
                }
              }));

            case 2:
            case "end":
              return _context5.stop();
          }
        }
      }, _callee5);
    }));

    return function (_x3) {
      return _ref8.apply(this, arguments);
    };
  }());
  (0, _defineProperty2["default"])(this, "allAccounts", /*#__PURE__*/function () {
    var _ref10 = (0, _asyncToGenerator2["default"])( /*#__PURE__*/_regenerator["default"].mark(function _callee6(_ref9) {
      var limit, startAfter;
      return _regenerator["default"].wrap(function _callee6$(_context6) {
        while (1) {
          switch (_context6.prev = _context6.next) {
            case 0:
              limit = _ref9.limit, startAfter = _ref9.startAfter;
              return _context6.abrupt("return", _this.client.queryContractSmart(_this.contractAddress, {
                all_accounts: {
                  limit: limit,
                  start_after: startAfter
                }
              }));

            case 2:
            case "end":
              return _context6.stop();
          }
        }
      }, _callee6);
    }));

    return function (_x4) {
      return _ref10.apply(this, arguments);
    };
  }());
  (0, _defineProperty2["default"])(this, "marketingInfo", /*#__PURE__*/(0, _asyncToGenerator2["default"])( /*#__PURE__*/_regenerator["default"].mark(function _callee7() {
    return _regenerator["default"].wrap(function _callee7$(_context7) {
      while (1) {
        switch (_context7.prev = _context7.next) {
          case 0:
            return _context7.abrupt("return", _this.client.queryContractSmart(_this.contractAddress, {
              marketing_info: {}
            }));

          case 1:
          case "end":
            return _context7.stop();
        }
      }
    }, _callee7);
  })));
  (0, _defineProperty2["default"])(this, "downloadLogo", /*#__PURE__*/(0, _asyncToGenerator2["default"])( /*#__PURE__*/_regenerator["default"].mark(function _callee8() {
    return _regenerator["default"].wrap(function _callee8$(_context8) {
      while (1) {
        switch (_context8.prev = _context8.next) {
          case 0:
            return _context8.abrupt("return", _this.client.queryContractSmart(_this.contractAddress, {
              download_logo: {}
            }));

          case 1:
          case "end":
            return _context8.stop();
        }
      }
    }, _callee8);
  })));
  this.client = client;
  this.contractAddress = contractAddress;
  this.balance = this.balance.bind(this);
  this.tokenInfo = this.tokenInfo.bind(this);
  this.minter = this.minter.bind(this);
  this.allowance = this.allowance.bind(this);
  this.allAllowances = this.allAllowances.bind(this);
  this.allAccounts = this.allAccounts.bind(this);
  this.marketingInfo = this.marketingInfo.bind(this);
  this.downloadLogo = this.downloadLogo.bind(this);
});
exports.Cw20QueryClient = Cw20QueryClient;