"use strict";

var _interopRequireDefault = require("@babel/runtime/helpers/interopRequireDefault");

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.OracleQueryClient = exports.OracleClient = void 0;

var _regenerator = _interopRequireDefault(require("@babel/runtime/regenerator"));

var _assertThisInitialized2 = _interopRequireDefault(require("@babel/runtime/helpers/assertThisInitialized"));

var _inherits2 = _interopRequireDefault(require("@babel/runtime/helpers/inherits"));

var _possibleConstructorReturn2 = _interopRequireDefault(require("@babel/runtime/helpers/possibleConstructorReturn"));

var _getPrototypeOf2 = _interopRequireDefault(require("@babel/runtime/helpers/getPrototypeOf"));

var _asyncToGenerator2 = _interopRequireDefault(require("@babel/runtime/helpers/asyncToGenerator"));

var _createClass2 = _interopRequireDefault(require("@babel/runtime/helpers/createClass"));

var _classCallCheck2 = _interopRequireDefault(require("@babel/runtime/helpers/classCallCheck"));

var _defineProperty2 = _interopRequireDefault(require("@babel/runtime/helpers/defineProperty"));

function _createSuper(Derived) { var hasNativeReflectConstruct = _isNativeReflectConstruct(); return function _createSuperInternal() { var Super = (0, _getPrototypeOf2["default"])(Derived), result; if (hasNativeReflectConstruct) { var NewTarget = (0, _getPrototypeOf2["default"])(this).constructor; result = Reflect.construct(Super, arguments, NewTarget); } else { result = Super.apply(this, arguments); } return (0, _possibleConstructorReturn2["default"])(this, result); }; }

function _isNativeReflectConstruct() { if (typeof Reflect === "undefined" || !Reflect.construct) return false; if (Reflect.construct.sham) return false; if (typeof Proxy === "function") return true; try { Boolean.prototype.valueOf.call(Reflect.construct(Boolean, [], function () {})); return true; } catch (e) { return false; } }

/**
 * This file was automatically generated by cosmwasm-typescript-gen@0.3.6.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the cosmwasm-typescript-gen generate command to regenerate this file.
 */
var OracleQueryClient = /*#__PURE__*/(0, _createClass2["default"])(function OracleQueryClient(client, contractAddress) {
  var _this = this;

  (0, _classCallCheck2["default"])(this, OracleQueryClient);
  (0, _defineProperty2["default"])(this, "client", void 0);
  (0, _defineProperty2["default"])(this, "contractAddress", void 0);
  (0, _defineProperty2["default"])(this, "config", /*#__PURE__*/(0, _asyncToGenerator2["default"])( /*#__PURE__*/_regenerator["default"].mark(function _callee() {
    return _regenerator["default"].wrap(function _callee$(_context) {
      while (1) {
        switch (_context.prev = _context.next) {
          case 0:
            return _context.abrupt("return", _this.client.queryContractSmart(_this.contractAddress, {
              config: {}
            }));

          case 1:
          case "end":
            return _context.stop();
        }
      }
    }, _callee);
  })));
  (0, _defineProperty2["default"])(this, "feeder", /*#__PURE__*/function () {
    var _ref3 = (0, _asyncToGenerator2["default"])( /*#__PURE__*/_regenerator["default"].mark(function _callee2(_ref2) {
      var asset;
      return _regenerator["default"].wrap(function _callee2$(_context2) {
        while (1) {
          switch (_context2.prev = _context2.next) {
            case 0:
              asset = _ref2.asset;
              return _context2.abrupt("return", _this.client.queryContractSmart(_this.contractAddress, {
                feeder: {
                  asset: asset
                }
              }));

            case 2:
            case "end":
              return _context2.stop();
          }
        }
      }, _callee2);
    }));

    return function (_x) {
      return _ref3.apply(this, arguments);
    };
  }());
  (0, _defineProperty2["default"])(this, "price", /*#__PURE__*/function () {
    var _ref5 = (0, _asyncToGenerator2["default"])( /*#__PURE__*/_regenerator["default"].mark(function _callee3(_ref4) {
      var base, quote;
      return _regenerator["default"].wrap(function _callee3$(_context3) {
        while (1) {
          switch (_context3.prev = _context3.next) {
            case 0:
              base = _ref4.base, quote = _ref4.quote;
              return _context3.abrupt("return", _this.client.queryContractSmart(_this.contractAddress, {
                price: {
                  base: base,
                  quote: quote
                }
              }));

            case 2:
            case "end":
              return _context3.stop();
          }
        }
      }, _callee3);
    }));

    return function (_x2) {
      return _ref5.apply(this, arguments);
    };
  }());
  (0, _defineProperty2["default"])(this, "prices", /*#__PURE__*/function () {
    var _ref7 = (0, _asyncToGenerator2["default"])( /*#__PURE__*/_regenerator["default"].mark(function _callee4(_ref6) {
      var limit, startAfter;
      return _regenerator["default"].wrap(function _callee4$(_context4) {
        while (1) {
          switch (_context4.prev = _context4.next) {
            case 0:
              limit = _ref6.limit, startAfter = _ref6.startAfter;
              return _context4.abrupt("return", _this.client.queryContractSmart(_this.contractAddress, {
                prices: {
                  limit: limit,
                  start_after: startAfter
                }
              }));

            case 2:
            case "end":
              return _context4.stop();
          }
        }
      }, _callee4);
    }));

    return function (_x3) {
      return _ref7.apply(this, arguments);
    };
  }());
  this.client = client;
  this.contractAddress = contractAddress;
  this.config = this.config.bind(this);
  this.feeder = this.feeder.bind(this);
  this.price = this.price.bind(this);
  this.prices = this.prices.bind(this);
});
exports.OracleQueryClient = OracleQueryClient;

var OracleClient = /*#__PURE__*/function (_OracleQueryClient) {
  (0, _inherits2["default"])(OracleClient, _OracleQueryClient);

  var _super = _createSuper(OracleClient);

  function OracleClient(client, sender, contractAddress) {
    var _this2;

    (0, _classCallCheck2["default"])(this, OracleClient);
    _this2 = _super.call(this, client, contractAddress);
    (0, _defineProperty2["default"])((0, _assertThisInitialized2["default"])(_this2), "client", void 0);
    (0, _defineProperty2["default"])((0, _assertThisInitialized2["default"])(_this2), "sender", void 0);
    (0, _defineProperty2["default"])((0, _assertThisInitialized2["default"])(_this2), "contractAddress", void 0);
    (0, _defineProperty2["default"])((0, _assertThisInitialized2["default"])(_this2), "updateConfig", /*#__PURE__*/function () {
      var _ref9 = (0, _asyncToGenerator2["default"])( /*#__PURE__*/_regenerator["default"].mark(function _callee5(_ref8) {
        var owner,
            fee,
            memo,
            funds,
            _args5 = arguments;
        return _regenerator["default"].wrap(function _callee5$(_context5) {
          while (1) {
            switch (_context5.prev = _context5.next) {
              case 0:
                owner = _ref8.owner;
                fee = _args5.length > 1 && _args5[1] !== undefined ? _args5[1] : "auto";
                memo = _args5.length > 2 ? _args5[2] : undefined;
                funds = _args5.length > 3 ? _args5[3] : undefined;
                _context5.next = 6;
                return _this2.client.execute(_this2.sender, _this2.contractAddress, {
                  update_config: {
                    owner: owner
                  }
                }, fee, memo, funds);

              case 6:
                return _context5.abrupt("return", _context5.sent);

              case 7:
              case "end":
                return _context5.stop();
            }
          }
        }, _callee5);
      }));

      return function (_x4) {
        return _ref9.apply(this, arguments);
      };
    }());
    (0, _defineProperty2["default"])((0, _assertThisInitialized2["default"])(_this2), "registerFeeder", /*#__PURE__*/function () {
      var _ref11 = (0, _asyncToGenerator2["default"])( /*#__PURE__*/_regenerator["default"].mark(function _callee6(_ref10) {
        var asset,
            feeder,
            fee,
            memo,
            funds,
            _args6 = arguments;
        return _regenerator["default"].wrap(function _callee6$(_context6) {
          while (1) {
            switch (_context6.prev = _context6.next) {
              case 0:
                asset = _ref10.asset, feeder = _ref10.feeder;
                fee = _args6.length > 1 && _args6[1] !== undefined ? _args6[1] : "auto";
                memo = _args6.length > 2 ? _args6[2] : undefined;
                funds = _args6.length > 3 ? _args6[3] : undefined;
                _context6.next = 6;
                return _this2.client.execute(_this2.sender, _this2.contractAddress, {
                  register_feeder: {
                    asset: asset,
                    feeder: feeder
                  }
                }, fee, memo, funds);

              case 6:
                return _context6.abrupt("return", _context6.sent);

              case 7:
              case "end":
                return _context6.stop();
            }
          }
        }, _callee6);
      }));

      return function (_x5) {
        return _ref11.apply(this, arguments);
      };
    }());
    (0, _defineProperty2["default"])((0, _assertThisInitialized2["default"])(_this2), "feedPrice", /*#__PURE__*/function () {
      var _ref13 = (0, _asyncToGenerator2["default"])( /*#__PURE__*/_regenerator["default"].mark(function _callee7(_ref12) {
        var assets,
            prices,
            fee,
            memo,
            funds,
            _args7 = arguments;
        return _regenerator["default"].wrap(function _callee7$(_context7) {
          while (1) {
            switch (_context7.prev = _context7.next) {
              case 0:
                assets = _ref12.assets, prices = _ref12.prices;
                fee = _args7.length > 1 && _args7[1] !== undefined ? _args7[1] : "auto";
                memo = _args7.length > 2 ? _args7[2] : undefined;
                funds = _args7.length > 3 ? _args7[3] : undefined;
                _context7.next = 6;
                return _this2.client.execute(_this2.sender, _this2.contractAddress, {
                  feed_price: {
                    assets: assets,
                    prices: prices
                  }
                }, fee, memo, funds);

              case 6:
                return _context7.abrupt("return", _context7.sent);

              case 7:
              case "end":
                return _context7.stop();
            }
          }
        }, _callee7);
      }));

      return function (_x6) {
        return _ref13.apply(this, arguments);
      };
    }());
    _this2.client = client;
    _this2.sender = sender;
    _this2.contractAddress = contractAddress;
    _this2.updateConfig = _this2.updateConfig.bind((0, _assertThisInitialized2["default"])(_this2));
    _this2.registerFeeder = _this2.registerFeeder.bind((0, _assertThisInitialized2["default"])(_this2));
    _this2.feedPrice = _this2.feedPrice.bind((0, _assertThisInitialized2["default"])(_this2));
    return _this2;
  }

  return (0, _createClass2["default"])(OracleClient);
}(OracleQueryClient);

exports.OracleClient = OracleClient;