"use strict";

var _interopRequireDefault = require("@babel/runtime/helpers/interopRequireDefault");

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.PTokenQueryClient = exports.PTokenClient = void 0;

var _regenerator = _interopRequireDefault(require("@babel/runtime/regenerator"));

var _assertThisInitialized2 = _interopRequireDefault(require("@babel/runtime/helpers/assertThisInitialized"));

var _inherits2 = _interopRequireDefault(require("@babel/runtime/helpers/inherits"));

var _possibleConstructorReturn2 = _interopRequireDefault(require("@babel/runtime/helpers/possibleConstructorReturn"));

var _getPrototypeOf2 = _interopRequireDefault(require("@babel/runtime/helpers/getPrototypeOf"));

var _asyncToGenerator2 = _interopRequireDefault(require("@babel/runtime/helpers/asyncToGenerator"));

var _createClass2 = _interopRequireDefault(require("@babel/runtime/helpers/createClass"));

var _classCallCheck2 = _interopRequireDefault(require("@babel/runtime/helpers/classCallCheck"));

var _defineProperty2 = _interopRequireDefault(require("@babel/runtime/helpers/defineProperty"));

function _createSuper(Derived) { var hasNativeReflectConstruct = _isNativeReflectConstruct(); return function _createSuperInternal() { var Super = (0, _getPrototypeOf2["default"])(Derived), result; if (hasNativeReflectConstruct) { var NewTarget = (0, _getPrototypeOf2["default"])(this).constructor; result = Reflect.construct(Super, arguments, NewTarget); } else { result = Super.apply(this, arguments); } return (0, _possibleConstructorReturn2["default"])(this, result); }; }

function _isNativeReflectConstruct() { if (typeof Reflect === "undefined" || !Reflect.construct) return false; if (Reflect.construct.sham) return false; if (typeof Proxy === "function") return true; try { Boolean.prototype.valueOf.call(Reflect.construct(Boolean, [], function () {})); return true; } catch (e) { return false; } }

/**
* This file was automatically generated by cosmwasm-typescript-gen@0.3.6.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the cosmwasm-typescript-gen generate command to regenerate this file.
*/
var PTokenQueryClient = /*#__PURE__*/(0, _createClass2["default"])(function PTokenQueryClient(client, contractAddress) {
  var _this = this;

  (0, _classCallCheck2["default"])(this, PTokenQueryClient);
  (0, _defineProperty2["default"])(this, "client", void 0);
  (0, _defineProperty2["default"])(this, "contractAddress", void 0);
  (0, _defineProperty2["default"])(this, "balance", /*#__PURE__*/function () {
    var _ref2 = (0, _asyncToGenerator2["default"])( /*#__PURE__*/_regenerator["default"].mark(function _callee(_ref) {
      var address;
      return _regenerator["default"].wrap(function _callee$(_context) {
        while (1) {
          switch (_context.prev = _context.next) {
            case 0:
              address = _ref.address;
              return _context.abrupt("return", _this.client.queryContractSmart(_this.contractAddress, {
                balance: {
                  address: address
                }
              }));

            case 2:
            case "end":
              return _context.stop();
          }
        }
      }, _callee);
    }));

    return function (_x) {
      return _ref2.apply(this, arguments);
    };
  }());
  (0, _defineProperty2["default"])(this, "tokenInfo", /*#__PURE__*/(0, _asyncToGenerator2["default"])( /*#__PURE__*/_regenerator["default"].mark(function _callee2() {
    return _regenerator["default"].wrap(function _callee2$(_context2) {
      while (1) {
        switch (_context2.prev = _context2.next) {
          case 0:
            return _context2.abrupt("return", _this.client.queryContractSmart(_this.contractAddress, {
              token_info: {}
            }));

          case 1:
          case "end":
            return _context2.stop();
        }
      }
    }, _callee2);
  })));
  (0, _defineProperty2["default"])(this, "minter", /*#__PURE__*/(0, _asyncToGenerator2["default"])( /*#__PURE__*/_regenerator["default"].mark(function _callee3() {
    return _regenerator["default"].wrap(function _callee3$(_context3) {
      while (1) {
        switch (_context3.prev = _context3.next) {
          case 0:
            return _context3.abrupt("return", _this.client.queryContractSmart(_this.contractAddress, {
              minter: {}
            }));

          case 1:
          case "end":
            return _context3.stop();
        }
      }
    }, _callee3);
  })));
  (0, _defineProperty2["default"])(this, "allowance", /*#__PURE__*/function () {
    var _ref6 = (0, _asyncToGenerator2["default"])( /*#__PURE__*/_regenerator["default"].mark(function _callee4(_ref5) {
      var owner, spender;
      return _regenerator["default"].wrap(function _callee4$(_context4) {
        while (1) {
          switch (_context4.prev = _context4.next) {
            case 0:
              owner = _ref5.owner, spender = _ref5.spender;
              return _context4.abrupt("return", _this.client.queryContractSmart(_this.contractAddress, {
                allowance: {
                  owner: owner,
                  spender: spender
                }
              }));

            case 2:
            case "end":
              return _context4.stop();
          }
        }
      }, _callee4);
    }));

    return function (_x2) {
      return _ref6.apply(this, arguments);
    };
  }());
  (0, _defineProperty2["default"])(this, "allAllowances", /*#__PURE__*/function () {
    var _ref8 = (0, _asyncToGenerator2["default"])( /*#__PURE__*/_regenerator["default"].mark(function _callee5(_ref7) {
      var limit, owner, startAfter;
      return _regenerator["default"].wrap(function _callee5$(_context5) {
        while (1) {
          switch (_context5.prev = _context5.next) {
            case 0:
              limit = _ref7.limit, owner = _ref7.owner, startAfter = _ref7.startAfter;
              return _context5.abrupt("return", _this.client.queryContractSmart(_this.contractAddress, {
                all_allowances: {
                  limit: limit,
                  owner: owner,
                  start_after: startAfter
                }
              }));

            case 2:
            case "end":
              return _context5.stop();
          }
        }
      }, _callee5);
    }));

    return function (_x3) {
      return _ref8.apply(this, arguments);
    };
  }());
  (0, _defineProperty2["default"])(this, "allAccounts", /*#__PURE__*/function () {
    var _ref10 = (0, _asyncToGenerator2["default"])( /*#__PURE__*/_regenerator["default"].mark(function _callee6(_ref9) {
      var limit, startAfter;
      return _regenerator["default"].wrap(function _callee6$(_context6) {
        while (1) {
          switch (_context6.prev = _context6.next) {
            case 0:
              limit = _ref9.limit, startAfter = _ref9.startAfter;
              return _context6.abrupt("return", _this.client.queryContractSmart(_this.contractAddress, {
                all_accounts: {
                  limit: limit,
                  start_after: startAfter
                }
              }));

            case 2:
            case "end":
              return _context6.stop();
          }
        }
      }, _callee6);
    }));

    return function (_x4) {
      return _ref10.apply(this, arguments);
    };
  }());
  (0, _defineProperty2["default"])(this, "marketingInfo", /*#__PURE__*/(0, _asyncToGenerator2["default"])( /*#__PURE__*/_regenerator["default"].mark(function _callee7() {
    return _regenerator["default"].wrap(function _callee7$(_context7) {
      while (1) {
        switch (_context7.prev = _context7.next) {
          case 0:
            return _context7.abrupt("return", _this.client.queryContractSmart(_this.contractAddress, {
              marketing_info: {}
            }));

          case 1:
          case "end":
            return _context7.stop();
        }
      }
    }, _callee7);
  })));
  (0, _defineProperty2["default"])(this, "downloadLogo", /*#__PURE__*/(0, _asyncToGenerator2["default"])( /*#__PURE__*/_regenerator["default"].mark(function _callee8() {
    return _regenerator["default"].wrap(function _callee8$(_context8) {
      while (1) {
        switch (_context8.prev = _context8.next) {
          case 0:
            return _context8.abrupt("return", _this.client.queryContractSmart(_this.contractAddress, {
              download_logo: {}
            }));

          case 1:
          case "end":
            return _context8.stop();
        }
      }
    }, _callee8);
  })));
  this.client = client;
  this.contractAddress = contractAddress;
  this.balance = this.balance.bind(this);
  this.tokenInfo = this.tokenInfo.bind(this);
  this.minter = this.minter.bind(this);
  this.allowance = this.allowance.bind(this);
  this.allAllowances = this.allAllowances.bind(this);
  this.allAccounts = this.allAccounts.bind(this);
  this.marketingInfo = this.marketingInfo.bind(this);
  this.downloadLogo = this.downloadLogo.bind(this);
});
exports.PTokenQueryClient = PTokenQueryClient;

var PTokenClient = /*#__PURE__*/function (_PTokenQueryClient) {
  (0, _inherits2["default"])(PTokenClient, _PTokenQueryClient);

  var _super = _createSuper(PTokenClient);

  function PTokenClient(client, sender, contractAddress) {
    var _this2;

    (0, _classCallCheck2["default"])(this, PTokenClient);
    _this2 = _super.call(this, client, contractAddress);
    (0, _defineProperty2["default"])((0, _assertThisInitialized2["default"])(_this2), "client", void 0);
    (0, _defineProperty2["default"])((0, _assertThisInitialized2["default"])(_this2), "sender", void 0);
    (0, _defineProperty2["default"])((0, _assertThisInitialized2["default"])(_this2), "contractAddress", void 0);
    (0, _defineProperty2["default"])((0, _assertThisInitialized2["default"])(_this2), "transfer", /*#__PURE__*/function () {
      var _ref14 = (0, _asyncToGenerator2["default"])( /*#__PURE__*/_regenerator["default"].mark(function _callee9(_ref13) {
        var amount,
            recipient,
            fee,
            memo,
            funds,
            _args9 = arguments;
        return _regenerator["default"].wrap(function _callee9$(_context9) {
          while (1) {
            switch (_context9.prev = _context9.next) {
              case 0:
                amount = _ref13.amount, recipient = _ref13.recipient;
                fee = _args9.length > 1 && _args9[1] !== undefined ? _args9[1] : "auto";
                memo = _args9.length > 2 ? _args9[2] : undefined;
                funds = _args9.length > 3 ? _args9[3] : undefined;
                _context9.next = 6;
                return _this2.client.execute(_this2.sender, _this2.contractAddress, {
                  transfer: {
                    amount: amount,
                    recipient: recipient
                  }
                }, fee, memo, funds);

              case 6:
                return _context9.abrupt("return", _context9.sent);

              case 7:
              case "end":
                return _context9.stop();
            }
          }
        }, _callee9);
      }));

      return function (_x5) {
        return _ref14.apply(this, arguments);
      };
    }());
    (0, _defineProperty2["default"])((0, _assertThisInitialized2["default"])(_this2), "burn", /*#__PURE__*/function () {
      var _ref16 = (0, _asyncToGenerator2["default"])( /*#__PURE__*/_regenerator["default"].mark(function _callee10(_ref15) {
        var amount,
            user,
            fee,
            memo,
            funds,
            _args10 = arguments;
        return _regenerator["default"].wrap(function _callee10$(_context10) {
          while (1) {
            switch (_context10.prev = _context10.next) {
              case 0:
                amount = _ref15.amount, user = _ref15.user;
                fee = _args10.length > 1 && _args10[1] !== undefined ? _args10[1] : "auto";
                memo = _args10.length > 2 ? _args10[2] : undefined;
                funds = _args10.length > 3 ? _args10[3] : undefined;
                _context10.next = 6;
                return _this2.client.execute(_this2.sender, _this2.contractAddress, {
                  burn: {
                    amount: amount,
                    user: user
                  }
                }, fee, memo, funds);

              case 6:
                return _context10.abrupt("return", _context10.sent);

              case 7:
              case "end":
                return _context10.stop();
            }
          }
        }, _callee10);
      }));

      return function (_x6) {
        return _ref16.apply(this, arguments);
      };
    }());
    (0, _defineProperty2["default"])((0, _assertThisInitialized2["default"])(_this2), "send", /*#__PURE__*/function () {
      var _ref18 = (0, _asyncToGenerator2["default"])( /*#__PURE__*/_regenerator["default"].mark(function _callee11(_ref17) {
        var amount,
            contract,
            msg,
            fee,
            memo,
            funds,
            _args11 = arguments;
        return _regenerator["default"].wrap(function _callee11$(_context11) {
          while (1) {
            switch (_context11.prev = _context11.next) {
              case 0:
                amount = _ref17.amount, contract = _ref17.contract, msg = _ref17.msg;
                fee = _args11.length > 1 && _args11[1] !== undefined ? _args11[1] : "auto";
                memo = _args11.length > 2 ? _args11[2] : undefined;
                funds = _args11.length > 3 ? _args11[3] : undefined;
                _context11.next = 6;
                return _this2.client.execute(_this2.sender, _this2.contractAddress, {
                  send: {
                    amount: amount,
                    contract: contract,
                    msg: msg
                  }
                }, fee, memo, funds);

              case 6:
                return _context11.abrupt("return", _context11.sent);

              case 7:
              case "end":
                return _context11.stop();
            }
          }
        }, _callee11);
      }));

      return function (_x7) {
        return _ref18.apply(this, arguments);
      };
    }());
    (0, _defineProperty2["default"])((0, _assertThisInitialized2["default"])(_this2), "increaseAllowance", /*#__PURE__*/function () {
      var _ref20 = (0, _asyncToGenerator2["default"])( /*#__PURE__*/_regenerator["default"].mark(function _callee12(_ref19) {
        var amount,
            expires,
            spender,
            fee,
            memo,
            funds,
            _args12 = arguments;
        return _regenerator["default"].wrap(function _callee12$(_context12) {
          while (1) {
            switch (_context12.prev = _context12.next) {
              case 0:
                amount = _ref19.amount, expires = _ref19.expires, spender = _ref19.spender;
                fee = _args12.length > 1 && _args12[1] !== undefined ? _args12[1] : "auto";
                memo = _args12.length > 2 ? _args12[2] : undefined;
                funds = _args12.length > 3 ? _args12[3] : undefined;
                _context12.next = 6;
                return _this2.client.execute(_this2.sender, _this2.contractAddress, {
                  increase_allowance: {
                    amount: amount,
                    expires: expires,
                    spender: spender
                  }
                }, fee, memo, funds);

              case 6:
                return _context12.abrupt("return", _context12.sent);

              case 7:
              case "end":
                return _context12.stop();
            }
          }
        }, _callee12);
      }));

      return function (_x8) {
        return _ref20.apply(this, arguments);
      };
    }());
    (0, _defineProperty2["default"])((0, _assertThisInitialized2["default"])(_this2), "decreaseAllowance", /*#__PURE__*/function () {
      var _ref22 = (0, _asyncToGenerator2["default"])( /*#__PURE__*/_regenerator["default"].mark(function _callee13(_ref21) {
        var amount,
            expires,
            spender,
            fee,
            memo,
            funds,
            _args13 = arguments;
        return _regenerator["default"].wrap(function _callee13$(_context13) {
          while (1) {
            switch (_context13.prev = _context13.next) {
              case 0:
                amount = _ref21.amount, expires = _ref21.expires, spender = _ref21.spender;
                fee = _args13.length > 1 && _args13[1] !== undefined ? _args13[1] : "auto";
                memo = _args13.length > 2 ? _args13[2] : undefined;
                funds = _args13.length > 3 ? _args13[3] : undefined;
                _context13.next = 6;
                return _this2.client.execute(_this2.sender, _this2.contractAddress, {
                  decrease_allowance: {
                    amount: amount,
                    expires: expires,
                    spender: spender
                  }
                }, fee, memo, funds);

              case 6:
                return _context13.abrupt("return", _context13.sent);

              case 7:
              case "end":
                return _context13.stop();
            }
          }
        }, _callee13);
      }));

      return function (_x9) {
        return _ref22.apply(this, arguments);
      };
    }());
    (0, _defineProperty2["default"])((0, _assertThisInitialized2["default"])(_this2), "transferFrom", /*#__PURE__*/function () {
      var _ref24 = (0, _asyncToGenerator2["default"])( /*#__PURE__*/_regenerator["default"].mark(function _callee14(_ref23) {
        var amount,
            owner,
            recipient,
            fee,
            memo,
            funds,
            _args14 = arguments;
        return _regenerator["default"].wrap(function _callee14$(_context14) {
          while (1) {
            switch (_context14.prev = _context14.next) {
              case 0:
                amount = _ref23.amount, owner = _ref23.owner, recipient = _ref23.recipient;
                fee = _args14.length > 1 && _args14[1] !== undefined ? _args14[1] : "auto";
                memo = _args14.length > 2 ? _args14[2] : undefined;
                funds = _args14.length > 3 ? _args14[3] : undefined;
                _context14.next = 6;
                return _this2.client.execute(_this2.sender, _this2.contractAddress, {
                  transfer_from: {
                    amount: amount,
                    owner: owner,
                    recipient: recipient
                  }
                }, fee, memo, funds);

              case 6:
                return _context14.abrupt("return", _context14.sent);

              case 7:
              case "end":
                return _context14.stop();
            }
          }
        }, _callee14);
      }));

      return function (_x10) {
        return _ref24.apply(this, arguments);
      };
    }());
    (0, _defineProperty2["default"])((0, _assertThisInitialized2["default"])(_this2), "sendFrom", /*#__PURE__*/function () {
      var _ref26 = (0, _asyncToGenerator2["default"])( /*#__PURE__*/_regenerator["default"].mark(function _callee15(_ref25) {
        var amount,
            contract,
            msg,
            owner,
            fee,
            memo,
            funds,
            _args15 = arguments;
        return _regenerator["default"].wrap(function _callee15$(_context15) {
          while (1) {
            switch (_context15.prev = _context15.next) {
              case 0:
                amount = _ref25.amount, contract = _ref25.contract, msg = _ref25.msg, owner = _ref25.owner;
                fee = _args15.length > 1 && _args15[1] !== undefined ? _args15[1] : "auto";
                memo = _args15.length > 2 ? _args15[2] : undefined;
                funds = _args15.length > 3 ? _args15[3] : undefined;
                _context15.next = 6;
                return _this2.client.execute(_this2.sender, _this2.contractAddress, {
                  send_from: {
                    amount: amount,
                    contract: contract,
                    msg: msg,
                    owner: owner
                  }
                }, fee, memo, funds);

              case 6:
                return _context15.abrupt("return", _context15.sent);

              case 7:
              case "end":
                return _context15.stop();
            }
          }
        }, _callee15);
      }));

      return function (_x11) {
        return _ref26.apply(this, arguments);
      };
    }());
    (0, _defineProperty2["default"])((0, _assertThisInitialized2["default"])(_this2), "burnFrom", /*#__PURE__*/function () {
      var _ref28 = (0, _asyncToGenerator2["default"])( /*#__PURE__*/_regenerator["default"].mark(function _callee16(_ref27) {
        var amount,
            owner,
            fee,
            memo,
            funds,
            _args16 = arguments;
        return _regenerator["default"].wrap(function _callee16$(_context16) {
          while (1) {
            switch (_context16.prev = _context16.next) {
              case 0:
                amount = _ref27.amount, owner = _ref27.owner;
                fee = _args16.length > 1 && _args16[1] !== undefined ? _args16[1] : "auto";
                memo = _args16.length > 2 ? _args16[2] : undefined;
                funds = _args16.length > 3 ? _args16[3] : undefined;
                _context16.next = 6;
                return _this2.client.execute(_this2.sender, _this2.contractAddress, {
                  burn_from: {
                    amount: amount,
                    owner: owner
                  }
                }, fee, memo, funds);

              case 6:
                return _context16.abrupt("return", _context16.sent);

              case 7:
              case "end":
                return _context16.stop();
            }
          }
        }, _callee16);
      }));

      return function (_x12) {
        return _ref28.apply(this, arguments);
      };
    }());
    (0, _defineProperty2["default"])((0, _assertThisInitialized2["default"])(_this2), "mint", /*#__PURE__*/function () {
      var _ref30 = (0, _asyncToGenerator2["default"])( /*#__PURE__*/_regenerator["default"].mark(function _callee17(_ref29) {
        var amount,
            recipient,
            fee,
            memo,
            funds,
            _args17 = arguments;
        return _regenerator["default"].wrap(function _callee17$(_context17) {
          while (1) {
            switch (_context17.prev = _context17.next) {
              case 0:
                amount = _ref29.amount, recipient = _ref29.recipient;
                fee = _args17.length > 1 && _args17[1] !== undefined ? _args17[1] : "auto";
                memo = _args17.length > 2 ? _args17[2] : undefined;
                funds = _args17.length > 3 ? _args17[3] : undefined;
                _context17.next = 6;
                return _this2.client.execute(_this2.sender, _this2.contractAddress, {
                  mint: {
                    amount: amount,
                    recipient: recipient
                  }
                }, fee, memo, funds);

              case 6:
                return _context17.abrupt("return", _context17.sent);

              case 7:
              case "end":
                return _context17.stop();
            }
          }
        }, _callee17);
      }));

      return function (_x13) {
        return _ref30.apply(this, arguments);
      };
    }());
    (0, _defineProperty2["default"])((0, _assertThisInitialized2["default"])(_this2), "updateMarketing", /*#__PURE__*/function () {
      var _ref32 = (0, _asyncToGenerator2["default"])( /*#__PURE__*/_regenerator["default"].mark(function _callee18(_ref31) {
        var description,
            marketing,
            project,
            fee,
            memo,
            funds,
            _args18 = arguments;
        return _regenerator["default"].wrap(function _callee18$(_context18) {
          while (1) {
            switch (_context18.prev = _context18.next) {
              case 0:
                description = _ref31.description, marketing = _ref31.marketing, project = _ref31.project;
                fee = _args18.length > 1 && _args18[1] !== undefined ? _args18[1] : "auto";
                memo = _args18.length > 2 ? _args18[2] : undefined;
                funds = _args18.length > 3 ? _args18[3] : undefined;
                _context18.next = 6;
                return _this2.client.execute(_this2.sender, _this2.contractAddress, {
                  update_marketing: {
                    description: description,
                    marketing: marketing,
                    project: project
                  }
                }, fee, memo, funds);

              case 6:
                return _context18.abrupt("return", _context18.sent);

              case 7:
              case "end":
                return _context18.stop();
            }
          }
        }, _callee18);
      }));

      return function (_x14) {
        return _ref32.apply(this, arguments);
      };
    }());
    (0, _defineProperty2["default"])((0, _assertThisInitialized2["default"])(_this2), "uploadLogo", /*#__PURE__*/(0, _asyncToGenerator2["default"])( /*#__PURE__*/_regenerator["default"].mark(function _callee19() {
      var fee,
          memo,
          funds,
          _args19 = arguments;
      return _regenerator["default"].wrap(function _callee19$(_context19) {
        while (1) {
          switch (_context19.prev = _context19.next) {
            case 0:
              fee = _args19.length > 0 && _args19[0] !== undefined ? _args19[0] : "auto";
              memo = _args19.length > 1 ? _args19[1] : undefined;
              funds = _args19.length > 2 ? _args19[2] : undefined;
              _context19.next = 5;
              return _this2.client.execute(_this2.sender, _this2.contractAddress, {
                upload_logo: {}
              }, fee, memo, funds);

            case 5:
              return _context19.abrupt("return", _context19.sent);

            case 6:
            case "end":
              return _context19.stop();
          }
        }
      }, _callee19);
    })));
    _this2.client = client;
    _this2.sender = sender;
    _this2.contractAddress = contractAddress;
    _this2.transfer = _this2.transfer.bind((0, _assertThisInitialized2["default"])(_this2));
    _this2.burn = _this2.burn.bind((0, _assertThisInitialized2["default"])(_this2));
    _this2.send = _this2.send.bind((0, _assertThisInitialized2["default"])(_this2));
    _this2.increaseAllowance = _this2.increaseAllowance.bind((0, _assertThisInitialized2["default"])(_this2));
    _this2.decreaseAllowance = _this2.decreaseAllowance.bind((0, _assertThisInitialized2["default"])(_this2));
    _this2.transferFrom = _this2.transferFrom.bind((0, _assertThisInitialized2["default"])(_this2));
    _this2.sendFrom = _this2.sendFrom.bind((0, _assertThisInitialized2["default"])(_this2));
    _this2.burnFrom = _this2.burnFrom.bind((0, _assertThisInitialized2["default"])(_this2));
    _this2.mint = _this2.mint.bind((0, _assertThisInitialized2["default"])(_this2));
    _this2.updateMarketing = _this2.updateMarketing.bind((0, _assertThisInitialized2["default"])(_this2));
    _this2.uploadLogo = _this2.uploadLogo.bind((0, _assertThisInitialized2["default"])(_this2));
    return _this2;
  }

  return (0, _createClass2["default"])(PTokenClient);
}(PTokenQueryClient);

exports.PTokenClient = PTokenClient;